# shashankg-1nt21is413-ml-lab-report-logistic-regression-student-uni-dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
col_names=['x1','x2','result']
data = pd.read_csv("/home/ignis/413/data-set/Student-University(For Logistic Regression Program).csv",names=col_names)

In [3]:
data.head

<bound method NDFrame.head of            x1         x2  result
0   34.623660  78.024693       0
1   30.286711  43.894998       0
2   35.847409  72.902198       0
3   60.182599  86.308552       1
4   79.032736  75.344376       1
..        ...        ...     ...
95  83.489163  48.380286       1
96  42.261701  87.103851       1
97  99.315009  68.775409       1
98  55.340018  64.931938       1
99  74.775893  89.529813       1

[100 rows x 3 columns]>

In [4]:
print(data)
x = data.iloc[:,[0,1]].values
y = data.iloc[:,2].values

           x1         x2  result
0   34.623660  78.024693       0
1   30.286711  43.894998       0
2   35.847409  72.902198       0
3   60.182599  86.308552       1
4   79.032736  75.344376       1
..        ...        ...     ...
95  83.489163  48.380286       1
96  42.261701  87.103851       1
97  99.315009  68.775409       1
98  55.340018  64.931938       1
99  74.775893  89.529813       1

[100 rows x 3 columns]


In [5]:
x

array([[34.62365962, 78.02469282],
       [30.28671077, 43.89499752],
       [35.84740877, 72.90219803],
       [60.18259939, 86.3085521 ],
       [79.03273605, 75.34437644],
       [45.08327748, 56.31637178],
       [61.10666454, 96.51142588],
       [75.02474557, 46.55401354],
       [76.0987867 , 87.42056972],
       [84.43281996, 43.53339331],
       [95.86155507, 38.22527806],
       [75.01365839, 30.60326323],
       [82.30705337, 76.4819633 ],
       [69.36458876, 97.71869196],
       [39.53833914, 76.03681085],
       [53.97105215, 89.20735014],
       [69.07014406, 52.74046973],
       [67.94685548, 46.67857411],
       [70.66150955, 92.92713789],
       [76.97878373, 47.57596365],
       [67.37202755, 42.83843832],
       [89.67677575, 65.79936593],
       [50.53478829, 48.85581153],
       [34.21206098, 44.2095286 ],
       [77.92409145, 68.97235999],
       [62.27101367, 69.95445795],
       [80.19018075, 44.82162893],
       [93.1143888 , 38.80067034],
       [61.83020602,

In [6]:
y

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1])

In [7]:
xp=preprocessing.scale(x)
kf=KFold(n_splits=5)

In [8]:
for train_index,test_index in kf.split(xp):
    xtrain,xtest,ytrain,ytest=train_test_split(xp,y,test_size=0.20,random_state=0)
    x1=xtrain[:,0]
    x2=xtrain[:,1]
    b0=0.0
    b1=0.0
    b2=0.0
    epoch=100
    alpha=0.001
    while(epoch>0):
        for i in range(len(xtrain)):
            prediction=1/(1+np.exp(-(b0+b1*x1[i]+b2*x2[i])))
            b0=b0+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*1.0
            b1=b1+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x1[i]
            b2=b2+alpha*(ytrain[i]-prediction)*prediction*(1-prediction)*x2[i]
        epoch=epoch-1
        print(b0)
        print(b1)
        print(b2)

0.0019948281725557983
0.005482531972233602
0.005544755419849717
0.003977543227052592
0.010936676472719009
0.011061238086772042
0.005948080973156311
0.016362266488006375
0.016549290983486464
0.007906383552040102
0.021759149314370507
0.022008770586704206
0.00985239931755479
0.027127186313723645
0.027439546637175405
0.011786082711940515
0.03246625265646178
0.03284150189778506
0.013707394136594558
0.03777623705237219
0.038214531900733754
0.015616299818402372
0.04305704147071598
0.04355854468482554
0.01751277167212845
0.04830858085058014
0.04887346052386708
0.019396787159352023
0.05353078280257157
0.05415921164716242
0.02126832914441921
0.058723587302899304
0.05941574195306194
0.02312738574786884
0.0638869463808623
0.06464300671649897
0.02497395019777337
0.0690208238007288
0.06984097229141732
0.026808020679419637
0.07412519473895886
0.07500961580896186
0.02862960018373704
0.07920004545768576
0.08014892487227171
0.030438696354862023
0.08424537297533509
0.08525889724868033
0.03223532133720985

0.11698304052340303
0.33341817864201145
0.3384119410076398
0.11815427725359556
0.33691869696334903
0.3419785985623065
0.1193173711174423
0.34039888365280524
0.3455247405942038
0.12047240353573926
0.34385892123312395
0.3490505439373636
0.1216194553659004
0.3472989911319922
0.35255618444526005
0.12275860688810324
0.35071927364600575
0.35604183695529196
0.12388993779250483
0.3541199479071378
0.35950767525561933
0.1250135271674815
0.3575011918516028
0.3629538720542621
0.1261294534888484
0.3608631821910199
0.3663805989503681
0.1272377946100152
0.3642060943857782
0.369788026407561
0.12833862775303634
0.36753010262050784
0.37317632372928283
0.12943202950051527
0.37083537978156883
0.37654565903604426
0.13051807578832472
0.3741220974364702
0.3798961992445035
0.13159684189910398
0.3773904258151309
0.38322811004829277
0.13266840245649691
0.3806405337929037
0.38654155590051925
0.13373283142009634
0.3838725888752779
0.38983669999786114
0.13479020208106038
0.38708675718418994
0.39311370426619263
0.1

0.1216194553659004
0.3472989911319922
0.35255618444526005
0.12275860688810324
0.35071927364600575
0.35604183695529196
0.12388993779250483
0.3541199479071378
0.35950767525561933
0.1250135271674815
0.3575011918516028
0.3629538720542621
0.1261294534888484
0.3608631821910199
0.3663805989503681
0.1272377946100152
0.3642060943857782
0.369788026407561
0.12833862775303634
0.36753010262050784
0.37317632372928283
0.12943202950051527
0.37083537978156883
0.37654565903604426
0.13051807578832472
0.3741220974364702
0.3798961992445035
0.13159684189910398
0.3773904258151309
0.38322811004829277
0.13266840245649691
0.3806405337929037
0.38654155590051925
0.13373283142009634
0.3838725888752779
0.38983669999786114
0.13479020208106038
0.38708675718418994
0.39311370426619263
0.1358405870583669
0.39028320344586187
0.3963727293476664
0.13688405829567815
0.39346209098009854
0.3996139345891848
0.13792068705878002
0.3966235816909739
0.40283747803219944
0.1389505439335714
0.39976783605883964
0.40604351640377373
0.1

In [9]:
final_prediction=[]
x3=xtest[:,0]
x4=xtest[:,1]
print(ytest)

[1 0 0 0 1 1 1 1 0 1 0 0 0 1 1 1 0 1 1 1]


In [10]:
y_pred=[0]*len(xtest)

In [11]:
print(y_pred)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [12]:
for i in range(len(xtest)):
    y_pred[i]=np.round(1/(1+np.exp(-(b0+b1*x3[i]+b2*x4[i]))))
    print(y_pred[i])

0.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0


In [13]:
final_prediction.append(np.ceil(y_pred[i]))
print(final_prediction)

[1.0]


In [14]:
accuracy = accuracy_score(ytest,y_pred)

In [15]:
print(accuracy)

0.8
